import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "@/styles/globals.css";
import NextAuthProvider from "@/store/change/modify/NextAuthProvider";
const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type Props = {
	children: React.ReactNode;
};

const RootLayout = ({ children }: Props) => {
	return (
		<html lang="en">
			<body className={jakarta.className}>
				<NextAuthProvider>{children}</NextAuthProvider>
			</body>
		</html>
	);
};

export default RootLayout;
