import { ThemeProvider } from "@/components/school/theme";
import { ReactQueryProvider } from "@/providers/school/react-query/provider";
import { ReduxProvider } from "@/providers/school/redux/provider";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "@/styles/globals.css";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "AdvancedPractice",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider
			signInFallbackRedirectUrl="/school/group/create"
			signUpFallbackRedirectUrl="/school/group/create"
		>
			<html lang="en" suppressHydrationWarning>
				<body className={`${jakarta.className} bg-black z-40`}>
					<ThemeProvider
						attribute="class"
						defaultTheme="dark"
						disableTransitionOnChange
					>
						<ReduxProvider>
							<ReactQueryProvider>{children}</ReactQueryProvider>
						</ReduxProvider>
						<Toaster />
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
