# Generated by Django 5.1 on 2024-10-06 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaljotauth", "0002_alter_customusermodel_userid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="userId",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=64,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="username",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
