version: "3"

services:
    nexusconjure:
        build:
            context: .
            args:
                SUNO_COOKIE: ${SUNO_COOKIE}
        volumes:
            - ./public:/app/public
        ports:
            - "3000:3000"
