---
services:
  web:
    build:
      context: .
      args:
        - PYTHON_VERSION=3.12-slim-bullseye
        - PROJ_NAME=portaljot-logic
    image: portaljot-logic_web
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgres://user:password@db:5432/portaljot-logic
      - PATH=/opt/venv/bin:$PATH
    depends_on:
      - db
    volumes:
      - ./src:/code
    command: /bin/bash -c "/code/paracord_runner.sh"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=portaljot-logic
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data:

x-build-steps: &build-steps
  FROM python:${PYTHON_VERSION}
  RUN python -m venv /opt/venv
  ENV PATH=/opt/venv/bin:$PATH
  RUN pip install --upgrade pip
  ENV PYTHONDONTWRITEBYTECODE 1
  ENV PYTHONUNBUFFERED 1
  RUN apt-get update && apt-get install -y \
      libpq-dev \
      libjpeg-dev \
      libcairo2 \
      gcc \
      && rm -rf /var/lib/apt/lists/*
  RUN mkdir -p /code
  WORKDIR /code
  COPY requirements.txt /tmp/requirements.txt
  COPY ./src /code
  RUN pip install -r /tmp/requirements.txt
  RUN pip install gunicorn
  ARG PROJ_NAME
  RUN printf "#!/bin/bash\n" > /code/paracord_runner.sh && \
      printf "RUN_PORT=\"\${PORT:-8000}\"\n\n" >> /code/paracord_runner.sh && \
      printf "python manage.py migrate --no-input\n" >> /code/paracord_runner.sh && \
      printf "gunicorn ${PROJ_NAME}.wsgi:application --bind \"0.0.0.0:\$RUN_PORT\"\n" >> /code/paracord_runner.sh
  RUN chmod +x /code/paracord_runner.sh
  RUN apt-get remove --purge -y \
      && apt-get autoremove -y \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*

services:
  web:
    build:
      context: .
      dockerfile_inline: |
        <<: *build-steps