# Generated by Django 5.1 on 2024-10-06 23:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portaljotauth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="userId",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=32,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="customusermodel",
            name="username",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
