# Generated by Django 5.1 on 2025-01-03 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "portaljotauth",
            "0005_remove_customusermodel_portaljotau_email_503378_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="customerId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="emailVerified",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="firstname",
            field=models.CharField(default="Mor", max_length=30),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="lastname",
            field=models.CharField(default="More", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="role",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="stripeId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="customusermodel",
            index=models.Index(fields=["email"], name="portaljotau_email_503378_idx"),
        ),
        migrations.AddIndex(
            model_name="customusermodel",
            index=models.Index(
                fields=["username"], name="portaljotau_usernam_e8806a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customusermodel",
            index=models.Index(fields=["userId"], name="portaljotau_userId_3210bf_idx"),
        ),
    ]
