# Generated by Django 5.1 on 2025-01-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portaljotauth", "0006_customusermodel_customerid_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customusermodel",
            name="portaljotau_email_503378_idx",
        ),
        migrations.RemoveIndex(
            model_name="customusermodel",
            name="portaljotau_usernam_e8806a_idx",
        ),
        migrations.RemoveIndex(
            model_name="customusermodel",
            name="portaljotau_userId_3210bf_idx",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="customerId",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="emailVerified",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="image",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="lastname",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="role",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="stripeId",
        ),
    ]
