import { Provider } from "@/components/LLPMG/ContactForm";

export const states = [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY",
];

export const pharmacies = [
    "CVS",
    "Walgreens",
    "Walmart",
    "Rite Aid",
    "Safeway",
    "Kroger",
    "Target Pharmacy",
    "Costco Pharmacy",
    "Albertsons",
    "Vons",
];

export const reasons = [
    "New Patient Registration",
    "Follow-up Appointment",
    "Prescription Refill",
    "Mental Health Consultation",
    "Therapy Session",
    "Other",
];

// export const providers: Provider[] = [
//     {
//         providerName: "Mubashir Farooqi",
//         title: "Psychiatrist",
//         providerPhone: "8582099593",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "M.D.",
//     },
//     {
//         providerName: "Liberty Olive RB Macias",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "DNP, PMHNP-BC",
//     },
//     {
//         providerName: "Uloma Anozie",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "DNP",
//     },
//     {
//         providerName: "Carolyn Alexander",
//         title: "Psychotherapist",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "LMFT",
//     },
//     {
//         providerName: "Jonathan Clay",
//         title: "Nurse Practitioner",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "PMHNP-BC",
//     },
//     {
//         providerName: "Edmund Young",
//         title: "Psychotherapist",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "Ed.D, LCSW, M.S.G, B.C.D",
//     },
//     {
//         providerName: "Don W. Kreger",
//         title: "Psychologist",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "Ph.D",
//     },
//     {
//         providerName: "Tatum David",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "PMHNP-BC",
//     },
//     {
//         providerName: "Nashwa Moustafa",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "PMHNP-BC",
//     },
//     {
//         providerName: "Grace Somoso",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "PMHNP-BC",
//     },
//     // {
//     //     providerName: "Adaobi Adimorah",
//     //     title: "Psychiatric Nurse Practitioner",
//     //     providerPhone: "9099006465",
//     //     providerEmail: "llpmg@lomalindapsych.com",
//     //     degree: "PMHNP-BC",
//     // },
//     {
//         providerName: "Guy Biakop",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "PMHNP-BC",
//     },
//     {
//         providerName: "Joytila Singh",
//         title: "Psychiatrist",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "M.D.",
//     },
//     {
//         providerName: "Alex Capuchino",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "DNP",
//     },
//     {
//         providerName: "Martin Calixterio",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "6196234556",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "DNP",
//     },
//     {
//         providerName: "Chris Gray",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9514436008",
//         providerEmail: "crgray63@yahoo.com",
//         degree: "N.P., MSN",
//     },
//     {
//         providerName: "Gaddiel Sarmiento",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "M.S.N.",
//     },
//     {
//         providerName: "Daniel Padua",
//         title: "Psychiatrist",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "M.D.",
//     },
//     {
//         providerName: "Nelly Saucedo",
//         title: "Psychotherapist",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "LCSW",
//     },
//     {
//         providerName: "Marlene Millan",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "PMHNP-BC",
//     },
//     {
//         providerName: "Glenna Briney",
//         title: "Psychotherapist",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "LCSW",
//     },
//     {
//         providerName: "Maria Piedra",
//         title: "Psychologist",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "PhD",
//     },
//     {
//         providerName: "Yoggie Effendy",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9099006465",
//         providerEmail: "llpmg@lomalindapsych.com",
//         degree: "PMHNP-BC",
//     },
// ];

// export const providers: Provider[] = [
//     {
//         providerName: "Mubashir Farooqi",
//         title: "Psychiatrist",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "M.D.",
//     },
//     {
//         providerName: "Liberty Olive RB Macias",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "DNP, PMHNP-BC",
//     },
//     {
//         providerName: "Uloma Anozie",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "DNP",
//     },
//     {
//         providerName: "Carolyn Alexander",
//         title: "Psychotherapist",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "LMFT",
//     },
//     {
//         providerName: "Jonathan Clay",
//         title: "Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "PMHNP-BC",
//     },
//     {
//         providerName: "Edmund Young",
//         title: "Psychotherapist",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "Ed.D, LCSW, M.S.G, B.C.D",
//     },
//     {
//         providerName: "Don W. Kreger",
//         title: "Psychologist",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "Ph.D",
//     },
//     {
//         providerName: "Tatum David",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "PMHNP-BC",
//     },
//     {
//         providerName: "Nashwa Moustafa",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "PMHNP-BC",
//     },
//     {
//         providerName: "Grace Somoso",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "PMHNP-BC",
//     },
//     // {
//     //     providerName: "Adaobi Adimorah",
//     //     title: "Psychiatric Nurse Practitioner",
//     //     providerPhone: "9092130299",
//     //     providerEmail: "me@russellpalma.com",
//     //     degree: "PMHNP-BC",
//     // },
//     {
//         providerName: "Guy Biakop",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "PMHNP-BC",
//     },
//     {
//         providerName: "Joytila Singh",
//         title: "Psychiatrist",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "M.D.",
//     },
//     {
//         providerName: "Alex Capuchino",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "DNP",
//     },
//     {
//         providerName: "Martin Calixterio",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "DNP",
//     },
//     {
//         providerName: "Gaddiel Sarmiento",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "M.S.N.",
//     },
//     {
//         providerName: "Daniel Padua",
//         title: "Psychiatrist",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "M.D.",
//     },
//     {
//         providerName: "Nelly Saucedo",
//         title: "Psychotherapist",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "LCSW",
//     },
//     {
//         providerName: "Marlene Millan",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "PMHNP-BC",
//     },
//     {
//         providerName: "Glenna Briney",
//         title: "Psychotherapist",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "LCSW",
//     },
//     {
//         providerName: "Maria Piedra",
//         title: "Psychologist",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "PhD",
//     },
//     {
//         providerName: "Yoggie Effendy",
//         title: "Psychiatric Nurse Practitioner",
//         providerPhone: "9092130299",
//         providerEmail: "me@russellpalma.com",
//         degree: "PMHNP-BC",
//     },
// ];

export const providers: Provider[] = [
    {
        providerName: "Mubashir Farooqi",
        title: "Psychiatrist",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "M.D.",
    },
    {
        providerName: "Liberty Olive RB Macias",
        title: "Psychiatric Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "DNP, PMHNP-BC",
    },
    {
        providerName: "Uloma Anozie",
        title: "Psychiatric Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "DNP",
    },
    {
        providerName: "Carolyn Alexander",
        title: "Psychotherapist",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "LMFT",
    },
    {
        providerName: "Jonathan Clay",
        title: "Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "PMHNP-BC",
    },
    {
        providerName: "Edmund Young",
        title: "Psychotherapist",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "Ed.D, LCSW, M.S.G, B.C.D",
    },
    {
        providerName: "Don W. Kreger",
        title: "Psychologist",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "Ph.D",
    },
    {
        providerName: "Tatum David",
        title: "Psychiatric Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "PMHNP-BC",
    },
    {
        providerName: "Nashwa Moustafa",
        title: "Psychiatric Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "PMHNP-BC",
    },
    {
        providerName: "Grace Somoso",
        title: "Psychiatric Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "PMHNP-BC",
    },
    // {
    //     providerName: "Adaobi Adimorah",
    //     title: "Psychiatric Nurse Practitioner",
    //     providerPhone: "9092895924",
    //     providerEmail: "colton@lomalindapsych.com",
    //     degree: "PMHNP-BC",
    // },
    {
        providerName: "Guy Biakop",
        title: "Psychiatric Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "PMHNP-BC",
    },
    {
        providerName: "Joytila Singh",
        title: "Psychiatrist",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "M.D.",
    },
    {
        providerName: "Alex Capuchino",
        title: "Psychiatric Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "DNP",
    },
    {
        providerName: "Martin Calixterio",
        title: "Psychiatric Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "DNP",
    },
    {
        providerName: "Gaddiel Sarmiento",
        title: "Psychiatric Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "M.S.N.",
    },
    {
        providerName: "Daniel Padua",
        title: "Psychiatrist",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "M.D.",
    },
    {
        providerName: "Nelly Saucedo",
        title: "Psychotherapist",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "LCSW",
    },
    {
        providerName: "Marlene Millan",
        title: "Psychiatric Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "PMHNP-BC",
    },
    {
        providerName: "Glenna Briney",
        title: "Psychotherapist",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "LCSW",
    },
    {
        providerName: "Maria Piedra",
        title: "Psychologist",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "PhD",
    },
    {
        providerName: "Yoggie Effendy",
        title: "Psychiatric Nurse Practitioner",
        providerPhone: "9092895924",
        providerEmail: "colton@lomalindapsych.com",
        degree: "PMHNP-BC",
    },
];
